normalized progress tic and cleaned out old boilerplate comments

diff --git a/commands/file-contains/script b/commands/file-contains/script
--- a/commands/file-contains/script
+++ b/commands/file-contains/script
@@ -1,57 +1,16 @@
 #!/usr/bin/env bash
 
-# To implement this command, edit the "Command implementation" section below. 
-
-# Usage
-# -----
-
-# Comments prefixed with `#/` are managed by stubbs.
-# The `command` and `usage` comments describe the command
-# and show its options.
-# 
 #/ command: waitfor:file-contains: "wait for the file to contain message"
 #/ usage: rerun waitfor:file-contains  --interval <30>  --maxtry <10>  --file <>  --string <> 
+#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
+#/ option-variables: INTERVAL MAXTRY FILE STRING
 
-# Load common functions
-# ---------------------
-
-# Load the function library for this module.
-# This loads rerun functions, too.
 . $RERUN_MODULE_DIR/lib/functions.sh file-contains || { 
   echo >&2 "Failed loading function library." ; exit 1 ; 
 }
 
-# Error handling
-# ---------------
 
-# This script is designed to _fail-fast_.
-
-# Trap errors and exit. The call to `rerun_die` will print the
-# the error message and exit with the error command exit status. 
-
-trap 'rerun_die $? "*** command failed: waitfor:file-contains. ***"' ERR
-
-# Run [set] `nounset` to treat unset variables as errors. Set [pipefail]
-# so a pipeline return status is the value of the last 
-# (rightmost) command to exit with non-zero status.
-#
-# [set]: http://ss64.com/bash/set.html
-# [pipefail]: http://www.gnu.org/software/bash/manual/html_node/Pipelines.html
-
-set -o nounset -o pipefail
-
-# Command variables
-# -----------------
-
-# This command script can access the following variables
-# declared by `rerun` or by the option parser function.
-
-#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
-#/ option-variables: INTERVAL MAXTRY FILE STRING
-
-# The `rerun_options_parse` function processes the command line
-# arguments. Each accepted command line flag results in setting 
-# one the corresponding option variables.
+set -o errexit -o nounset -o pipefail
 
 rerun_options_parse "$@"
 
@@ -66,8 +25,8 @@ while (( count <= max ))
 do
     if ! grep "${STRING}" "$FILE"
     then  
-        # output a progress character.
-        printf >&2 "."; 
+        # output a progress string.
+        progress_tic "."; 
     else  
         # Success. Found the string in file.
         break; 
@@ -77,7 +36,8 @@ do
 
     # error out if reached max attempts.
     (( count == max )) && {
-        rerun_die 1 "FAIL: Reached max attempts to find string in $FILE. Exiting."
+        rerun_log warn "FAIL: Reached max attempts to find string in $FILE. Exiting."
+        exit 1
     }
     # wait interval before trying again.
     sleep "$sleep"
